[build]
  command = "npm install && NEXT_DISABLE_ESLINT_PLUGIN=true npm run build"
  
[build.environment]
  NODE_VERSION = "20"
  NEXT_DISABLE_ESLINT_PLUGIN = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"